name: Publish

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  publish:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master' &&
      github.event.workflow_run.event == 'push' &&
      github.repository == 'albertz/py_better_exchook'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install Python deps
      run: |
        echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
        pip3 install --user --upgrade pip build twine

    - run: python3 -m build

    # https://github.com/marketplace/actions/pypi-publish
    - name: Publish to PyPI
      # https://github.com/pypa/gh-action-pypi-publish/issues/112
      uses: pypa/gh-action-pypi-publish@release/v1.4
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
